[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Memória optimalizálás a neurális hálónak
board_build.partitions = huge_app.csv 

lib_deps =
    ; Ez a TensorFlow Lite Micro hivatalos portja ESP32-re
    tanakamasayuki/TensorFlowLite_ESP32 @ ^1.0.0
    adafruit/Adafruit MPU6050